[GLOBAL]
pants_version = "2.18.0"
colors = true
backend_packages = [
    "pants.backend.python",
    "pants.backend.experimental.python.lint.ruff",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.python.lint.docformatter",
]

[source]
root_patterns = [
    "/configs",
    "/src",
    "/tests",
]

[mypy]
args = ["--linecount-report=reports"]

[python]
interpreter_constraints = [">=3.10.*"]
