_target_: src.models.classifier_module.ClassifierModule

defaults:
  - loss: cross_entropy
  - optimizer: adam
  - scheduler: null
  - _self_

net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  cfg: [784, 128, 256, 64, 10]  # [input_size, hidden_layers..., output_size]
  batch_norm: true
  bias: true

compile: false

monitor: val/acc
mode: max
