_target_: src._eqprop.eqprop_module.EqPropMSELitModule

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.1
  momentum: 0.9

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src._eqprop.eqprop_backbone.AnalogEP2
  _partial_: true
  batch_size: ${data.batch_size}
  dims: ${eval:'[784*${model.scale_input}, 128, 10*${model.scale_output}]'}
  beta: 0.01
  solver:
    _target_: src.core.eqprop.solver.AnalogEqPropSolver
    _partial_: true
    amp_factor: 1.0
    beta: ${model.net.beta}
    strategy:
      _target_: src.core.eqprop.strategy.NewtonStrategy
      clip_threshold: 0.5
      attn_factor: 0.6
      amp_factor: ${model.net.solver.amp_factor}
      eps: 1e-7
      max_iter: 25
      atol: 1e-6
      activation:
        _target_: src.core.eqprop.eqprop_util.P3OTS
        Is: 4.352E-6
        Vth: 0.26
        Vl: 0.0
        Vr: 0.0

scale_input: 2
scale_output: 2
positive_w: true
bias: false
clip_weights: true
normalize_weights: true
min_w: 1e-6
max_w_gain: 0.28
accumulate_grad_batches: 1
