_target_: src.models.classifier_module.ClassifierModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

loss:
  _target_: torch.nn.CrossEntropyLoss

net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  cfg: [784, 128, 256, 64, 10]  # [input_size, hidden_layers..., output_size]
  batch_norm: true
  bias: true

compile: false

monitor: val/acc
mode: max
