# packages in environment at /home/sinnce/miniconda3/envs/aihw:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
aihwkit-gpu               0.9.1           py311h7b7c7b5_0    conda-forge
aiohappyeyeballs          2.3.5                    pypi_0    pypi
aiohttp                   3.10.3                   pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
anyio                     4.2.0           py311h06a4308_0
appdirs                   1.4.4              pyhd3eb1b0_0
arrow                     1.2.3           py311h06a4308_1
astroid                   3.2.2           py311h06a4308_0
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
attrs                     24.2.0                   pypi_0    pypi
backoff                   2.2.1           py311h06a4308_1
beautifulsoup4            4.12.3          py311h06a4308_0
blas                      1.0                         mkl
blessed                   1.20.0          py311h06a4308_0
boto3                     1.34.154        py311h06a4308_0
botocore                  1.34.154        py311h06a4308_0
brotli                    1.0.9                he6710b0_2
brotli-python             1.1.0           py311hb755f60_1    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
certifi                   2024.8.30       py311h06a4308_0
cffi                      1.17.0          py311ha8e6434_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           py311h06a4308_0
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0           py311hdb19cb5_0
croniter                  1.3.7           py311h06a4308_0
cuda-version              11.8                 h70ddcb2_3    conda-forge
cudatoolkit               11.8.0              h4ba93d1_13    conda-forge
cudnn                     8.9.7.29             hbc23b4c_3    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0
cyrus-sasl                2.1.28               h52b45da_1
dateutils                 0.6.12          py311h06a4308_0
dbus                      1.13.18              hb2f20db_0
debugpy                   1.8.5           py311hf86e51f_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
deepdiff                  7.0.1           py311h92b7b1e_0
dill                      0.3.8           py311h06a4308_0
docker-pycreds            0.4.0              pyhd3eb1b0_0
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h6a678d5_0
fastapi                   0.103.0         py311h06a4308_0
filelock                  3.15.4             pyhd8ed1ab_0    conda-forge
filterpy                  1.4.5                      py_1    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonttools                 4.51.0          py311h5eee18b_0
freetype                  2.12.1               h267a509_2    conda-forge
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.1           pyhff2d567_0    conda-forge
gitdb                     4.0.7              pyhd3eb1b0_0
gitpython                 3.1.43          py311h06a4308_0
glib                      2.78.4               h6a678d5_0
glib-tools                2.78.4               h6a678d5_0
gmp                       6.3.0                hac33072_2    conda-forge
gmpy2                     2.1.5           py311hc4f1f91_1    conda-forge
gst-plugins-base          1.14.1               h6a678d5_1
gstreamer                 1.14.1               h5eee18b_1
h11                       0.14.0          py311h06a4308_0
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hydra-core                1.4.0.dev1               pypi_0    pypi
hydra-zen                 0.13.0                   pypi_0    pypi
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       73.1                 h6a678d5_0
idna                      3.7                pyhd8ed1ab_0    conda-forge
importlib-metadata        8.2.0              pyha770c72_0    conda-forge
importlib_metadata        8.2.0                hd8ed1ab_0    conda-forge
inquirer                  3.1.4           py311h06a4308_0
ipykernel                 6.29.5             pyh3099207_0    conda-forge
ipython                   8.26.0             pyh707e725_0    conda-forge
isort                     5.13.2          py311h06a4308_0
itsdangerous              2.2.0           py311h06a4308_0
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jmespath                  1.0.1           py311h06a4308_0
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h5eee18b_3
jupyter_client            8.6.2              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py311h38be061_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4           py311h6a678d5_0
krb5                      1.20.1               h143b758_1
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20240116.2      cxx17_he02047a_1    conda-forge
libblas                   3.9.0            20_linux64_mkl    conda-forge
libcblas                  3.9.0            20_linux64_mkl    conda-forge
libclang                  14.0.6          default_hc6dbbc7_1
libclang13                14.0.6          default_he11475f_1
libcups                   2.4.2                h2d74bed_1
libdeflate                1.21                 h4bc722e_0    conda-forge
libedit                   3.1.20230828         h5eee18b_0
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgfortran-ng            14.1.0               h69a702a_0    conda-forge
libgfortran5              14.1.0               hc5f4f2c_0    conda-forge
libglib                   2.78.4               hdc74915_0
libhwloc                  2.11.1          default_hecaa2ac_1000    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             2.1.4                h166bdaf_0    conda-forge
liblapack                 3.9.0            20_linux64_mkl    conda-forge
libllvm14                 14.0.6               hdb19cb5_3
libmagma                  2.7.2                h09b5827_2    conda-forge
libmagma_sparse           2.7.2                h09b5827_3    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libpq                     12.17                hdbd6064_0
libprotobuf               4.25.3               h08a7969_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libtiff                   4.2.0                hecacb30_2
libtorch                  2.3.1           cuda118_h7aef8b2_300    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.48.0               hd590300_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.16                 hd590300_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.0.1                h097e994_2
libxml2                   2.13.1               hfdd30dd_2
libzlib                   1.2.13               h4ab18f5_6    conda-forge
lightning                 2.4.0                    pypi_0    pypi
lightning-cloud           0.5.57          py311h06a4308_0
lightning-utilities       0.11.6                   pypi_0    pypi
llvm-openmp               18.1.7               ha31de31_0    conda-forge
markdown-it-py            2.2.0           py311h06a4308_1
markupsafe                2.1.5           py311h459d7ec_0    conda-forge
matplotlib                3.8.4           py311h06a4308_0
matplotlib-base           3.8.4           py311ha02d727_0
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mccabe                    0.7.0              pyhd3eb1b0_0
mdurl                     0.1.0           py311h06a4308_0
mkl                       2023.2.0         h84fe81f_50496    conda-forge
mkl-service               2.4.0           py311h5eee18b_1
mkl_fft                   1.3.8           py311h5eee18b_0
mkl_random                1.2.4           py311hdb19cb5_0
mpc                       1.3.1                hfe3b2da_0    conda-forge
mpfr                      4.2.1                h38ae2d0_2    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
multidict                 6.0.5                    pypi_0    pypi
mysql                     5.7.24               h721c034_2
nccl                      2.22.3.1             hee583db_1    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
networkx                  3.3                pyhd8ed1ab_1    conda-forge
numpy                     1.26.4          py311h08b1b3b_0
numpy-base                1.26.4          py311hf175353_0
omegaconf                 2.4.0.dev3               pypi_0    pypi
openjpeg                  2.4.0                h9ca470c_2
openssl                   3.3.1                h4bc722e_2    conda-forge
ordered-set               4.1.0           py311h06a4308_0
orjson                    3.9.15          py311h97a8848_0
packaging                 24.1               pyhd8ed1ab_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pcre2                     10.42                hebb0a14_1
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.4.0          py311h5eee18b_0
pip                       24.2               pyhd8ed1ab_0    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
plotly                    5.24.1                   pypi_0    pypi
ply                       3.11            py311h06a4308_0
prompt-toolkit            3.0.47             pyha770c72_0    conda-forge
protobuf                  4.25.3          py311h7b78aeb_0    conda-forge
psutil                    6.0.0           py311h331c9d8_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.12         py311h5eee18b_1
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.8.0           py311h06a4308_0
pylint                    3.2.2           py311h06a4308_0
pyparsing                 3.0.9           py311h06a4308_0
pyqt                      5.15.10         py311h6a678d5_0
pyqt5-sip                 12.13.0         py311h5eee18b_0
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.9          hb806964_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-editor             1.0.4              pyhd3eb1b0_0
python-multipart          0.0.9           py311h06a4308_0
python_abi                3.11                    4_cp311    conda-forge
pytorch                   2.3.1           cuda118_py311h0047a46_300    conda-forge
pytorch-lightning         2.4.0                    pypi_0    pypi
pytz                      2024.1          py311h06a4308_0
pyyaml                    6.0.2                    pypi_0    pypi
pyzmq                     26.1.0          py311h759c1eb_0    conda-forge
qt-main                   5.15.2              h53bd1ea_10
readchar                  4.0.5           py311h06a4308_0
readline                  8.2                  h8228510_1    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rich                      13.7.1          py311h06a4308_0
s3transfer                0.10.1          py311h06a4308_0
scikit-learn              1.5.1           py311hd632256_0    conda-forge
scipy                     1.14.0          py311h517d4fd_1    conda-forge
sentry-sdk                1.9.0           py311h06a4308_0
setproctitle              1.2.2           py311h5eee18b_0
setuptools                72.1.0                   pypi_0    pypi
sip                       6.7.12          py311h6a678d5_0
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.6.1                h3400bea_1    conda-forge
smmap                     4.0.0              pyhd3eb1b0_0
sniffio                   1.3.0           py311h06a4308_0
soupsieve                 2.5             py311h06a4308_0
sqlite                    3.45.3               h5eee18b_0
src                       0.0.1                     dev_0    <develop>
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
starlette                 0.27.0          py311h06a4308_0
starsessions              1.3.0           py311h06a4308_0
sympy                     1.13.1          pypyh2585a3b_103    conda-forge
tbb                       2021.12.0            h434a139_3    conda-forge
tenacity                  9.0.0                    pypi_0    pypi
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomlkit                   0.11.1          py311h06a4308_0
torchmetrics              1.4.1                    pypi_0    pypi
torchvision               0.15.2          cuda118py311h4cc2eb7_0
tornado                   6.4.1           py311h331c9d8_0    conda-forge
tqdm                      4.66.5                   pypi_0    pypi
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
unicodedata2              15.1.0          py311h5eee18b_0
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
uvicorn                   0.20.0          py311h06a4308_0
wandb                     0.16.6             pyhd8ed1ab_1    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
websocket-client          1.8.0           py311h06a4308_0
websockets                10.4            py311h5eee18b_1
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.4.6                h5eee18b_1
yaml                      0.2.5                h7b6447c_0
yarl                      1.9.4                    pypi_0    pypi
zeromq                    4.3.5                h6a678d5_0
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstandard                 0.23.0          py311h5cd10c7_0    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
